### ISSUE TITLE
Please kindly investigate.

### ISSUE THREAD

**Issue by multidev** [earthchie/DeFi-SDK#4]
I have run
node price_monitor.js
got the error message below.
I'm a newbie node js.
Thank you krub.

![image](https://user-images.githubusercontent.com/2812502/121437088-e7c57480-c9ab-11eb-87ce-db9501051c99.png)

**Comment by 9soraj** [comment]
https://github.com/zong09/DeFi-SDK/tree/feature/fixed-error-start-node

**Comment by multidev** [comment]
Thank you krub.

I just know  "module.exports"

Nice support.
